/*
 * SettingsExplorer.java
 *
 * Created on 30 January 2002, 19:17
 */

package alvahouse.eatool.gui;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import alvahouse.eatool.Application;
import alvahouse.eatool.util.SettingsManager;


/**
 *
 * @author  rbp28668
 */
public class SettingsExplorer extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    private final static String WINDOW_SETTINGS = "/Windows/SettingsExplorer";
    private Application app;
    
    /** Creates new form SettingsExplorer */
    public SettingsExplorer(SettingsManager.Element rt, Application app) {
        settings = rt;
        this.app = app;
        
        initComponents();
        
        setTitle("Settings Explorer");
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        setClosable(true);
        
        GUIBuilder.loadBounds(this,WINDOW_SETTINGS,app);
        
        root = buildTree(settings);
        treeModel = new DefaultTreeModel(root);
        tree.setModel(treeModel);
        
    }

    public void dispose() {
        GUIBuilder.saveBounds(this,WINDOW_SETTINGS,app);
        app.getWindowCoordinator().removeFrame(this);
    }
    
    private DefaultMutableTreeNode buildTree(SettingsManager.Element e) {
        DefaultMutableTreeNode node = new DefaultMutableTreeNode(e);
        for(String key : e.getAttributeKeys()){
            String value = e.attribute(key);
            DefaultMutableTreeNode nodeChild = new DefaultMutableTreeNode(key + " : " + value);
            node.add(nodeChild);
        }
        for(SettingsManager.Element element : e.getChildren()){
            DefaultMutableTreeNode nodeChild = buildTree(element);
            node.add(nodeChild);
        }
        return node;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        scrollPane = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        
        scrollPane.setViewportView(tree);
        
        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables

    private SettingsManager.Element settings;
    private DefaultTreeModel treeModel;
    private DefaultMutableTreeNode root;

}
